// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/ping.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var ping_default = defineTool({
  name: "ping",
  title: "Ping",
  description: "Health-check tool. Returns 'pong' and the current server time to verify MCP connectivity.",
  inputSchema: {
    message: z.string().optional().describe("Optional message to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ message }) => ({
    content: [
      {
        type: "text",
        text: `pong${message ? `: ${message}` : ""} \u2014 ${(/* @__PURE__ */ new Date()).toISOString()}`
      }
    ]
  })
});

// src/lib/mcp/tools/app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool2({
  name: "app_info",
  title: "App info",
  description: "Returns basic metadata about the Hyperkids app (name, description, public URL).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "HYPERKIDS",
            description: "HYPERKIDS \u2014 Athletic training, nutrition, program builder, competitions, and coaching platform.",
            url: "https://hyperkids.gr"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hyperkids-mcp",
  title: "Hyperkids MCP",
  version: "0.1.0",
  instructions: "MCP server for the Hyperkids athletic training platform. Use `ping` to verify connectivity and `app_info` to fetch basic app metadata. Additional tools can be added over time.",
  tools: [ping_default, app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
